---
- hosts: all
  vars:
    rbenv_default: 2.7.0
    rbenv_rubies:
      - { version: 2.7.0, opt: "" }
      - { version: 2.0.0-p648, opt: "{{ rbenv_old_ruby_configure_opt }}" }
  roles:
    - role: rbenv
    - role: nodejs
    - role: yarn
    - role: rails
