- name: install dependencies
  dnf:
    name:
      - bzip2
      - curl
      - gcc
      - gdbm-devel
      - git
      - libffi-devel
      - libyaml-devel
      - ncurses-devel
      - openssl-devel
      - readline-devel
      - zlib-devel
    enablerepo: PowerTools
    update_cache: true
  become: true

- name: clone repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/rbenv/rbenv.git",      dest: "{{ ansible_env.HOME }}/.rbenv" }
    - { repo: "https://github.com/rbenv/ruby-build.git", dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build" }

- name: profile
  blockinfile:
    marker: "# rbenv {mark}"
    path:   "{{ ansible_env.HOME }}/.bash_profile"
    block: |
      export PATH="{{ ansible_env.HOME }}/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

- name: check versions
  shell: /bin/bash -lc "{{ ansible_env.HOME }}/.rbenv/bin/rbenv versions --bare"
  register: rbenv_versions
  changed_when: false
  failed_when: false

- name: install ruby
  shell: /bin/bash -lc "{{ ansible_env.HOME }}/.rbenv/bin/rbenv install --skip-existing {{ item }}"
  with_items:
    - 2.7.0
  when: "item not in rbenv_versions.stdout"

- name: check global
  shell: /bin/bash -lc "{{ ansible_env.HOME }}/.rbenv/bin/rbenv global"
  register: rbenv_global
  changed_when: false
  failed_when: false

- name: set global
  shell: /bin/bash -lc "{{ ansible_env.HOME }}/.rbenv/bin/rbenv global 2.7.0 && {{ ansible_env.HOME }}/.rbenv/bin/rbenv rehash"
  when: "'2.7.0' not in rbenv_global.stdout"
